// a changer !
import Image from 'next/image'
import Head from 'next/head'
import { Logo } from '@/images/logo.svg'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { Blog } from '@/components/Blog'
import { Top } from '@/components/blog/Top'
import { TopTitre } from '@/components/blog/TopTitre'
import { List } from '@/components/blog/List'
import { Lien } from '@/components/blog/Lien'
import { VisitButton } from '@/components/button/VisitButton'

import { UserHeader } from '@/components/UserHeader'
import { ImagesGrid } from '@/components/blog/ImagesGrid'


import { IntroductionText } from '@/components/blog/IntroductionText'
import { Sujet } from '@/components/blog/Sujet'
import { Titre } from '@/components/blog/Titre'
import staticFile from "@/js/utils"
import Link from 'next/link'

const color = "indigo"


const sujet = "Crypto"
const titre = "Earning Crypto through Staking on Perpetual Protocol: A Beginner's Guide"
const description = "Learn how to earn passive income by staking your tokens on the Perpetual Protocol exchange. Follow these tips for maximizing your returns and choosing the best staking opportunities."


const exchange_name = "Perpetual Protocol"
const exchange_link = "https://app.perp.com?code=weknow"
const exchange_img = "https://img.freepik.com/free-vector/gradient-staking-illustration_23-2149390435.jpg?w=1380&t=st=1672137121~exp=1672137721~hmac=7e7e0ea13ba908a76675653dd5b1963b7fb3dc7c7738f7e43a985f41fe4ac393"

function Introduction(){
  return (
    <>
      <div className="mx-auto max-w-prose text-lg flex flex-col items-center">
        <UserHeader />
        
        <Sujet className={`text-${color}-500`}>{sujet}</Sujet>
        <Titre>{titre}</Titre>

        <Link target={"_blank"} href={exchange_link}>
          <img className='mt-5' alt="" src={exchange_img}/>
        </Link> 

        <VisitButton className={`bg-${color}-500 hover:bg-${color}-600`} href={exchange_link}>Visit {exchange_name}</VisitButton>
      
        <IntroductionText>{description}</IntroductionText>
      </div>
    </>
  )
}

function Contenu(){
  return (
    <>

  <div className='mt-10'>

  <h2>What is staking on Perpetual Protocol?</h2>
<p>Staking on Perpetual Protocol refers to holding certain tokens in your wallet and participating in the governance of the protocol. By doing so, you can earn a share of the transaction fees and rewards generated by the protocol. This is a passive income stream that requires minimal effort on your part, making it a popular choice for earning crypto on the Perpetual Protocol exchange.</p>
<h2>How do I start staking on Perpetual Protocol?</h2>
<p>To start staking on Perpetual Protocol, you'll first need to <a href="https://app.perp.com?code=weknow">create an account</a> and deposit the tokens you want to stake into your wallet. Then, you'll need to choose a staking pool or "validator" to join. Each validator has its own requirements and rewards structure, so make sure to do your research and choose one that aligns with your goals. Once you've chosen a validator, simply follow their instructions for staking your tokens and participating in governance.</p>
<h2>What are the best tokens to stake on Perpetual Protocol?</h2>
<p>The best tokens to stake on Perpetual Protocol will depend on your goals and risk tolerance. Some factors to consider when choosing a staking token include the staking yield (i.e., the percentage of rewards you can expect to earn), the stability of the token's price, and the token's potential for growth. <strong>Make sure to do your research and choose a token with a strong staking yield before getting started.</strong></p>
<h2>How can I maximize my staking returns on Perpetual Protocol?</h2>
<p>There are several ways to maximize your staking returns on Perpetual Protocol:</p>
<ul>
  <li>Choose a validator with a high staking yield.</li>
  <li>Stake for a longer period of time to compound your rewards.</li>
  <li>Consider staking a larger amount of tokens to increase your share of rewards.</li>
  <li>Stay up to date on market trends</li>
  </ul>

  </div>

    </>
  )
}

function Conclusion(){
  return (
    <>
    <VisitButton className={`bg-${color}-500 hover:bg-${color}-600`} href={exchange_link}>Visit {exchange_name}</VisitButton>
    </>
  )
}


function Content() {
  return (
    <div className="relative overflow-hidden bg-white py-16">
      <div className="hidden lg:absolute lg:inset-y-0 lg:block lg:h-full lg:w-full lg:[overflow-anchor:none]">
        <div className="relative mx-auto h-full max-w-prose text-lg" aria-hidden="true">
          <svg
            className="absolute top-12 left-full translate-x-32 transform"
            width={404}
            height={384}
            fill="none"
            viewBox="0 0 404 384"
          >
            <defs>
              <pattern
                id="74b3fd99-0a6f-4271-bef2-e80eeafdf357"
                x={0}
                y={0}
                width={20}
                height={20}
                patternUnits="userSpaceOnUse"
              >
                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
              </pattern>
            </defs>
            <rect width={404} height={384} fill="url(#74b3fd99-0a6f-4271-bef2-e80eeafdf357)" />
          </svg>
          <svg
            className="absolute top-1/2 right-full -translate-y-1/2 -translate-x-32 transform"
            width={404}
            height={384}
            fill="none"
            viewBox="0 0 404 384"
          >
            <defs>
              <pattern
                id="f210dbf6-a58d-4871-961e-36d5016a0f49"
                x={0}
                y={0}
                width={20}
                height={20}
                patternUnits="userSpaceOnUse"
              >
                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
              </pattern>
            </defs>
            <rect width={404} height={384} fill="url(#f210dbf6-a58d-4871-961e-36d5016a0f49)" />
          </svg>
          <svg
            className="absolute bottom-12 left-full translate-x-32 transform"
            width={404}
            height={384}
            fill="none"
            viewBox="0 0 404 384"
          >
            <defs>
              <pattern
                id="d3eb07ae-5182-43e6-857d-35c643af9034"
                x={0}
                y={0}
                width={20}
                height={20}
                patternUnits="userSpaceOnUse"
              >
                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
              </pattern>
            </defs>
            <rect width={404} height={384} fill="url(#d3eb07ae-5182-43e6-857d-35c643af9034)" />
          </svg>
        </div>
      </div>
      <div className="relative px-4 sm:px-6 lg:px-8 ">


        {/* Introduction */}
        <Introduction />

        {/* contenu */}
        <div className="prose prose-lg prose-indigo mx-auto text-gray-500 ">


          <Contenu />


          <div className='mt-20'>
            <Conclusion />
          </div>
        
        </div>
      </div>
    </div>
  )
}




export default function Home() {
  return (
    <>
      <Head>
        <link rel="icon" href={staticFile("favicon.ico")} type="image/x-icon" />
        <title>Weknow - {titre}</title>
        <meta httpEquiv='Content-Type' content="text/html; charset=utf-8" />
        <meta
          name="description"
          content={description}
        />
      </Head>
      <Header />
      <main>
        <Content />
        <Blog sujet={sujet} />
      </main>
      <Footer />
    </>
  )
}




